categories: [Sequence Analysis]
description: Generates multiple alignment of variant calls
name: vcf2pseudoalignment
owner: nml
remote_repository_url: http://irida.corefacility.ca/gitlab/analysis-pipelines/snvphyl-galaxy.git
