categories: [Sequence Analysis]
description: SNVPhyl suite defining all dependencies for SNVPhyl
name: suite_snvphyl
owner: nml
remote_repository_url: https://irida.corefacility.ca/analysis-pipelines/snvphyl-galaxy
