categories: [Sequence Analysis]
description: Generate matrix of SNP distances
name: snp_matrix
owner: nml
remote_repository_url: http://irida.corefacility.ca/gitlab/analysis-pipelines/snvphyl-galaxy.git
