categories: [Text Manipulation]
description: Use python regular expressions to find and replace text 
long_description: Use python regular expressions to find and replace text either in text lines or in columns of a tabular file
name: regex_find_replace
owner: nml
remote_repository_url: http://irida.corefacility.ca/gitlab/analysis-pipelines/snvphyl-galaxy.git
