categories: [Sequence Analysis]
description: Checks the mapping quality of all BAM(s)
name: verify_map
owner: nml
remote_repository_url: https://irida.corefacility.ca/analysis-pipelines/snvphyl-galaxy
