categories: [Sequence Analysis]
description: Checks the mapping quality of all BAM(s)
name: verify_map
owner: nml
remote_repository_url: http://irida.corefacility.ca/gitlab/analysis-pipelines/snvphyl-galaxy.git
